version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gin-app
    restart: always
    environment:
      - DB_USER
      - DB_PASS=43320
    expose:
      - 8080
    ports:
      - "8080:8080"
    depends_on:
      video-service-db:
        condition: service_started

  video-service-db:
    image: postgres:14
    container_name: video-service-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - env/db.env
    ports:
      - "5432:5432"

volumes:
  postgres_data: